[package]
authors = ["Gajo Petrovic <gajopetrovic@gmail.com>"]
edition = "2021"
name = "sprd"
version = "0.1.0"

[dependencies]
anyhow = "1.0"
clap = {version = "3.0.14", features = ["derive"]}
dirs = "4.0.0"
flate2 = "1.0.22"
hyper = {version = "0.14.16", features = ["client", "http1", "http2"]}
hyper-tls = "0.5.0"
indicatif = "0.16.2"
md-5 = "0.10.0"
reqwest = {version = "0.11", features = ["json"]}
serde = {version = "1.0.136", features = ["derive"]}
tempfile = "3.3.0"
thiserror = "1.0"
tokio = {version = "1.16.1", features = ["full"]}

[dev-dependencies]
test_utils = {path = "test_utils"}
