[package]
authors = ["Gajo Petrovic <gajopetrovic@gmail.com>"]
edition = "2021"
name = "sprd"
version = "0.1.0"

[dependencies]
clap = "3.0.14"
dirs = "4.0.0"
flate2 = "1.0.22"
hyper = "0.14.16"
hyper-tls = "0.5.0"
indicatif = "0.16.2"
md-5 = "0.10.0"
tempfile = "3.3.0"
tokio = {version = "1.16.1", features = ["full"]}
